[phases.setup]
nixPkgs = ["chromium", "nss", "nspr", "atk", "cups", "dbus", "expat", "libdrm", "libxkbcommon", "mesa", "pango", "cairo", "xorg.libX11", "xorg.libXcomposite", "xorg.libXdamage", "xorg.libXext", "xorg.libXfixes", "xorg.libXrandr", "xorg.libxcb"]

[variables]
PLAYWRIGHT_BROWSERS_PATH = "0"
PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = "1"
CHROMIUM_PATH = "/nix/store"
